services:
  app:
    image: cristophervergara/cvergara:latest
    container_name: my_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: my_postgres
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      REDIS_HOST: my_redis
      REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.10-alpine
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.7-alpine
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
