server:
  port: 8080

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  application:
    name: cvergara
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydb}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:mypassword}

  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  sql:
   init:
    mode: never # Deshabilita la inicialización automática de scripts SQL para evitar conflictos con Flyway

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydb}
    user: ${DB_USER:myuser}
    password: ${DB_PASSWORD:mypassword}
    locations: classpath:db/migration
    baseline-on-migrate: true


resilience4j:
  ratelimiter:
    instances:
      historyRateLimiter:
        limit-for-period: 3          # Número máximo de solicitudes
        limit-refresh-period: 60s     # Período de refresco (60 segundos)
        timeout-duration: 0s          # Tiempo de espera para arrojar fallo



logging:
  level:
    io.r2dbc: INFO
    io.r2dbc.postgresql: INFO
    org.springframework.data.r2dbc.core: INFO


